export const OTHER_OBJECTS = [
  'UnarmedCar',
  'ArmoredCar',
  'MedicalTruck',
  'FuelTruck',
  'AmmoTruck',
  'RepairTruck',
  'TankorAPC',
  'SmallHeli',
  'LargeTransportChopper',
  'MedicalChopper',
  'AirSupport1',
  'AirSupport2',
  'AITransportChopper',
  'AIExtractSupuportChopper',
  'FriendlyScoutVehicles',
  'FriendlyCheckpointUnits',
  'FriendlyFastResponseVehicles',
  'SupplySupportChopperOptions',
  'AirSupportOptions',
  'ArtiSupportOptions',
  'FriendlyVictims',
  'FriendlyUnarmedCar',
  'FriendlyMedicalTruck',
  'FriendlyArmoredCar',
  'FriendlyFuelTruck',
  'FriendlyJet',
  'FriendlyChopper',
];

export const FRIENDLY_UNIT_TYPES = [
  'Teamleader',
  'Rifleman',
  'Medic',
  'ATSpecialist',
  'Engineer',
  'AASpecialist',
  'ExplosiveSpecialist',
  'Autorifleman',
  'Spotter',
  'UAVOperator',
  'Pilot',
];

export const LOADOUT_COMMANDS = {
  forceAddUniform     : 'forceAddUniform',
  addItemToUniform    : 'addItemToUniform',
  addVest             : 'addVest',
  addItemToVest       : 'addItemToVest',
  addBackpack         : 'addBackpack',
  addItemToBackpack   : 'addItemToBackpack',
  addWeapon           : 'addWeapon',
  addPrimaryWeaponItem: 'addPrimaryWeaponItem',
  addHeadgear         : 'addHeadgear',
  addGoggles          : 'addGoggles',
  linkItem            : 'linkItem',
  setFace             : 'setFace',
  setSpeaker          : 'setSpeaker',
};

export const LOADOUT_DEFAULTS = {
  forceAddUniform     : 'U_BG_Guerilla1_1',
  addItemToUniform    : ['FirstAidKit', 'Chemlight_blue', 'Laserbatteries'],
  addVest             : 'V_Chestrig_oli',
  addItemToVest       : ['30Rnd_556x45_Stanag', '30Rnd_556x45_Stanag_Tracer_Yellow', '9Rnd_45ACP_Mag', 'HandGrenade'],
  addHeadgear         : 'H_Booniehat_khk',
  addWeapon           : ['arifle_Mk20_GL_F', 'hgun_ACPC2_F', 'launch_RPG32_F', 'Laserdesignator'],
  addPrimaryWeaponItem: ['optic_ACO_grn', 'acc_flashlight', 'bipod_03_F_blk'],
  linkItem            : ['ItemMap', 'ItemCompass', 'ItemWatch', 'ItemRadio', 'ItemGPS'],
  setFace             : 'GreekHead_A3_04',
  setSpeaker          : 'male01gre',
  addBackpack         : 'G_FieldPack_LAT',
  addItemToBackpack   : ['Medikit', '30Rnd_556x45_Stanag', 'RPG32_F', 'ToolKit'],
  addGoggles          : 'G_Shades_Black',
};

export const UNIT_DEFS = {
  Teamleader                  : 'Teamleader',
  Rifleman                    : 'Rifleman',
  Medic                       : 'Medic',
  ATSpecialist                : 'ATSpecialist',
  Engineer                    : 'Engineer',
  AASpecialist                : 'AASpecialist',
  ExplosiveSpecialist         : 'ExplosiveSpecialist',
  Autorifleman                : 'Autorifleman',
  Spotter                     : 'Spotter',
  UAVOperator                 : 'UAVOperator',
  Pilot                       : 'Pilot',
  '~'                         : 'otherObjects',
  UnarmedCar                  : 'Unarmed Car',
  ArmoredCar                  : 'Armed Car',
  MedicalTruck                : 'Medical Truck',
  FuelTruck                   : 'Fuel Truck',
  AmmoTruck                   : 'Ammo Truck',
  RepairTruck                 : 'Repair Truck',
  TankorAPC                   : 'Armored Vehicle',
  SmallHeli                   : 'Scout Helicopter',
  LargeTransportChopper       : 'Transport Helicopter',
  MedicalChopper              : 'Medical Helicopter',
  AirSupport1                 : 'Armed Support Helicopter',
  AirSupport2                 : 'Attack Helicopter',
  AITransportChopper          : 'AI Transportation Helicopter',
  AIExtractSupuportChopper    : 'AI Transportation Escort Helicopter',
  FriendlyScoutVehicles       : 'Checkpoint Scout Vehicles',
  FriendlyCheckpointUnits     : 'Checkpoint Units',
  FriendlyFastResponseVehicles: 'Checkpoint Transport Vehicles',
  SupplySupportChopperOptions : 'Supply Support Helicopter',
  AirSupportOptions           : 'Air Support Vehicles',
  ArtiSupportOptions          : 'Artillery Support Vehicles',
  FriendlyVictims             : 'Friendly POW Units',
  FriendlyUnarmedCar          : '(Mission Event) Unarmed Vehicles',
  FriendlyMedicalTruck        : '(Mission Event) Medical Vehicles',
  FriendlyArmoredCar          : '(Mission Event) Armored Vehicles',
  FriendlyFuelTruck           : '(Mission Event) Fuel Trucks',
  FriendlyJet                 : '(Mission Event) Air to Air Support Vehicles',
  FriendlyChopper             : '(Mission Event) Helicopters',
};

export const UNIT_DEFAULTS = {
  UnarmedCar                  : 'B_G_Offroad_01_F',
  ArmoredCar                  : 'B_G_Offroad_01_armed_F',
  MedicalTruck                : 'I_Truck_02_medical_F',
  FuelTruck                   : 'B_G_Van_01_fuel_F',
  AmmoTruck                   : 'I_Truck_02_ammo_F',
  RepairTruck                 : 'B_G_Offroad_01_repair_F',
  TankorAPC                   : 'B_G_Offroad_01_armed_F',
  SmallHeli                   : 'B_Heli_Light_01_F',
  LargeTransportChopper       : 'I_Heli_light_03_unarmed_F',
  MedicalChopper              : 'B_Heli_Transport_01_F',
  AirSupport1                 : 'B_Heli_Light_01_armed_F',
  AirSupport2                 : 'B_Heli_Light_01_armed_F',
  AITransportChopper          : 'I_Heli_light_03_unarmed_F',
  AIExtractSupuportChopper    : 'B_Heli_Attack_01_F',
  FriendlyScoutVehicles       : ['B_G_Offroad_01_F', 'B_G_Van_01_transport_F', 'B_G_Van_02_vehicle_F', 'B_G_Quadbike_01_F'],
  FriendlyCheckpointUnits     : ['B_G_Soldier_F'],
  FriendlyFastResponseVehicles: ['B_G_Offroad_01_F'],
  SupplySupportChopperOptions : ['B_Heli_Transport_03_unarmed_F'],
  AirSupportOptions           : ['B_Heli_Light_01_dynamicLoadout_F'],
  ArtiSupportOptions          : ['B_MBT_01_arty_F', 'B_MBT_01_mlrs_F'],
  FriendlyVictims             : ['B_G_Soldier_unarmed_F'],
  FriendlyUnarmedCar          : ['B_G_Van_01_transport_F'],
  FriendlyMedicalTruck        : ['B_G_Van_02_transport_F'],
  FriendlyArmoredCar          : ['B_G_Offroad_01_armed_F'],
  FriendlyFuelTruck           : ['B_G_Van_01_fuel_F'],
  FriendlyJet                 : ['B_Plane_Fighter_01_Stealth_F'],
  FriendlyChopper             : ['B_Heli_Transport_03_unarmed_F', 'B_Heli_Transport_01_camo_F', 'B_Heli_Attack_01_F'],
};
